### ISSUE TITLE
Time to Fix Wi-Fi

### ISSUE THREAD

**Issue by mohitmallick17** [Tonymiugrey/Garden-by-miugrey#27]
Before I start, I wanna tell you that I am fully aware that this laptop uses an unsupported Wi-Fi chip, Intel Wireless-AC 9560. My model is dk0047tx and yeah it also comes with Samsung-PM981 just like yours
I just booted today and was looking for the Wi-Fi settings to connect as the issue section doesn't says anything about Wi-Fi. In the end I could not find the settings in this close to perfect bootloader, really thank you miugrey for this amazing thread. I'd love to see more updates on this. While I was trying to boot with Opencore, it was an online method and I didn't really have an Ethernet. So my friend suggested me to [use this](https://github.com/OpenIntelWireless/itlwm) and I already had a working Wi-Fi, before even booting it. So what I did today was to copy this kext back to the clover bootloader, rebooted and Wi-Fi was working just fine. I downloaded chrome with it and was using Mac OS for about an hour since then. I did not find any issue even with adding the kext. Well I am not so sure why it isn't included or if it causes any problem that I am unaware of, but just in case you weren't aware that this kext exists I am opening this issue. Again, thank you so much for this beautiful repository. It just made my day when I found it. Cheers
Link to the itlwm.kext source code : [click here](https://github.com/OpenIntelWireless/itlwm)
Screenshot : [click here](https://imgur.com/a/IoIxAN6)

**Comment by arepson** [comment]
Are you using OC?

**Comment by Tonymiugrey** [comment]
You will find that repo in my github page haha. I forked it few months ago and at that time it just a buggy version with low speed network and unstable connection. As you know, things has been changed now.

I suggest you to try https://github.com/OpenIntelWireless/HeliPort , a cilent for itlwm.kext. I heard that it is stable now.

I have tried to make Intel WIFI work natively though AppleIntelWiFi, which will able to use the location service, but it makes battery drain out quickly, also not stable. I'm waiting it to be more stable because it will bring the experience that closer to Mac. Maybe it will support Airdrop in the future...

For me, the best choice is still to replace Intel WIFI card to the Broadcom's, or use the usb wifi because they're stable enough.

**Comment by mohitmallick17** [comment]
> You will find that repo in my github page haha. I forked it few months ago and at that time it just a buggy version with low speed network and unstable connection. As you know, things has been changed now.
> 
> I suggest you to try https://github.com/OpenIntelWireless/HeliPort , a cilent for itlwm.kext. I heard that it is stable now.
> 
> I have tried to make Intel WIFI work natively though AppleIntelWiFi, which will able to use the location service, but it makes battery drain out quickly, also not stable. I'm waiting it to be more stable because it will bring the experience that closer to Mac. Maybe it will support Airdrop in the future...
> 
> For me, the best choice is still to replace Intel WIFI card to the Broadcom's, or use the usb wifi because they're stable enough.

Hi. You're right. I am using HeliPort and it's quite stable and reliable, although this is still on pre-release but from what I've seen it does the job just fine. There's also an option to turn the wi-fi off when not needed. It serves my purpose all good. Whatever you do in the upcoming release I know it'll be for the best. Thanks again mate for this release. My mac is pretty much bugless just because of you. Good luck with your projects

**Comment by mohitmallick17** [comment]
> Are you using OC?

No, I am using clover from this repository :)
